version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: photodiary-app
    # 추가된 부분: 볼륨 매핑
    volumes:
      - ./uploads:/app/uploads
      - ./db_data:/app/data
    env_file:
      - .env
    restart: always